#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96 
STOP=96 
      
start_service() {   
    procd_open_instance          
    procd_set_param command /usr/local/usr/bin/esp_ubus
    procd_set_param pidfile /var/run/esp_ubus.pid                                                        
    procd_close_instance                                                                                                                                   
}                                                          
   
reload_service() {                           
	stop      
	start
}    
